select
directors,
count(*)as total_movies_directed,
sum(revenue)as total_revenue
from
(  
  select
  Director__1_ as directors,
  Revenue
  from `vast-tributary-407516.movies.movie_database`
  union all
  select
  Director__2_ as directors,
  Revenue
  from `vast-tributary-407516.movies.movie_database`) as movies_directed
where
directors is not null
group by directors
order by total_movies_directed desc
## this query shows the list of directors, total umber of movies they directed and the relationship between the directors and the revenue generated by the movies